{
 "title": "Micrometer",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(greeter_request_count_total{job=\"micrometer\"}[5m]))"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(greeter_request_count_total{job=\"micrometer\", status =~ \"5..\"}[5m])) / sum(rate(greeter_request_count_total{job=\"micrometer\"}[5m]))"
    }
   ]
  },
  {
   "title": "Duration in Seconds",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(greeter_request_duration_seconds_bucket{job = \"micrometer\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(greeter_request_duration_seconds_bucket{job = \"micrometer\"}[5m])) by (le))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(greeter_request_duration_seconds_bucket{job = \"micrometer\"}[5m])) by (le))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(greeter_request_duration_seconds_bucket{job = \"micrometer\"}[5m])) by (le))",
     "legendFormat": "0.99"
    }
   ]
  }
 ]
}